### ISSUE TITLE
Contar por linha aérea os voos que atrasaram

### ISSUE THREAD

**Issue by iagoscm** [iagoscm/eda-tp1#3]
- Fazer vetor com a struct criada anteriormente com um elemento por linha aérea, contendo os voos e os voos atrasados

**Comment by Neitan2001** [comment]
![image](https://user-images.githubusercontent.com/64803935/184144248-62800b05-7668-471a-b23a-e24a5ecf5162.png)

**Comment by Neitan2001** [comment]
Sugestão: utilizar a busca sequencial ordenada

**Comment by iagoscm** [comment]
- [x] Criar novo vetor rawData
- [ ] Comparar com os dadosOriginais
    - [ ] Se linha aérea já existe, somar os atrasos
    - [ ] Se linha aérea não existe, armazenar a nova linha aérea
